site_name: KumaraUpadhayayula DocsAsCode
theme:
    name: material
    locale: en
    features:
      - navigation.tracking
      - navigation.top
      - search.suggest
      - search.highlight
      - search.suggest
      - search.highlight
    palette:
      - scheme: default
        toggle:
          icon: material/toggle-switch-off-outline
          name: Switch to dark mode
      - scheme: slate
        toggle:
          icon: material/toggle-switch
          name: Switch to light mode
          primary: green
          accent: ambe


nav:
  - Home: 'index.md'
  - 'User Guide':
    - 'Nginx':
      - 'Nginx-Documentation': 'Nginx-Documentation.md'
